package com.agenthq.app.data.session

import com.agenthq.app.data.api.models.BranchRef
import com.agenthq.app.data.api.models.GitHubUser
import com.agenthq.app.data.api.models.Label
import com.agenthq.app.data.api.models.PullRequest
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test

class SessionInferenceEngineTest {

    private lateinit var engine: SessionInferenceEngine

    @Before
    fun setUp() {
        engine = SessionInferenceEngine()
    }

    // ── isCopilotSession ────────────────────────────────────────────

    @Test
    fun `isCopilotSession returns true when author is copilot bot`() {
        val pr = makePr(userLogin = "copilot[bot]")
        assertTrue(engine.isCopilotSession(pr))
    }

    @Test
    fun `isCopilotSession returns true when branch starts with copilot slash`() {
        val pr = makePr(headRef = "copilot/fix-bug-123")
        assertTrue(engine.isCopilotSession(pr))
    }

    @Test
    fun `isCopilotSession returns true when branch starts with agent slash`() {
        val pr = makePr(headRef = "agent/implement-feature")
        assertTrue(engine.isCopilotSession(pr))
    }

    @Test
    fun `isCopilotSession returns true when label contains copilot`() {
        val pr = makePr(labels = listOf(Label(1L, "copilot-generated", "0e8a16", null)))
        assertTrue(engine.isCopilotSession(pr))
    }

    @Test
    fun `isCopilotSession returns true when label contains agent`() {
        val pr = makePr(labels = listOf(Label(2L, "agent-session", "d73a4a", null)))
        assertTrue(engine.isCopilotSession(pr))
    }

    @Test
    fun `isCopilotSession returns true when body contains Generated by Copilot`() {
        val pr = makePr(body = "This PR was Generated by Copilot to fix issue #42.")
        assertTrue(engine.isCopilotSession(pr))
    }

    @Test
    fun `isCopilotSession returns true when body contains Co-authored-by Copilot`() {
        val pr = makePr(body = "Co-authored-by: Copilot\nSome changes.")
        assertTrue(engine.isCopilotSession(pr))
    }

    @Test
    fun `isCopilotSession returns false for regular PR`() {
        val pr = makePr()
        assertFalse(engine.isCopilotSession(pr))
    }

    @Test
    fun `isCopilotSession returns false when body is null`() {
        val pr = makePr(body = null)
        assertFalse(engine.isCopilotSession(pr))
    }

    // ── inferSessionMetadata ────────────────────────────────────────

    @Test
    fun `inferSessionMetadata returns UNKNOWN for non-copilot PR`() {
        val pr = makePr()
        val meta = engine.inferSessionMetadata(pr)
        assertEquals(SessionType.UNKNOWN, meta.sessionType)
        assertFalse(meta.isAutomated)
        assertNull(meta.issueReference)
        assertNull(meta.agentModel)
    }

    @Test
    fun `inferSessionMetadata marks copilot bot author as automated`() {
        val pr = makePr(userLogin = "copilot[bot]", body = "Fixes #99")
        val meta = engine.inferSessionMetadata(pr)
        assertEquals(SessionType.COPILOT_AGENT, meta.sessionType)
        assertTrue(meta.isAutomated)
    }

    @Test
    fun `inferSessionMetadata extracts issue reference from body`() {
        val pr = makePr(userLogin = "copilot[bot]", body = "Fixes #42")
        val meta = engine.inferSessionMetadata(pr)
        assertEquals("#42", meta.issueReference)
    }

    @Test
    fun `inferSessionMetadata extracts agent model from body`() {
        val pr = makePr(
            userLogin = "copilot[bot]",
            body = "Generated by Copilot\nModel: gpt-4o\nFixes #7"
        )
        val meta = engine.inferSessionMetadata(pr)
        assertEquals("gpt-4o", meta.agentModel)
    }

    @Test
    fun `inferSessionMetadata detects COPILOT_WORKSPACE session type`() {
        val pr = makePr(body = "Created in Copilot Workspace for feature X")
        val meta = engine.inferSessionMetadata(pr)
        assertEquals(SessionType.COPILOT_WORKSPACE, meta.sessionType)
        assertFalse(meta.isAutomated)
    }

    @Test
    fun `inferSessionMetadata is not automated for branch-only signal`() {
        val pr = makePr(headRef = "copilot/refactor-auth")
        val meta = engine.inferSessionMetadata(pr)
        assertEquals(SessionType.COPILOT_AGENT, meta.sessionType)
        assertFalse(meta.isAutomated)
    }

    // ── Helpers ─────────────────────────────────────────────────────

    private fun makePr(
        userLogin: String = "octocat",
        headRef: String = "feature/my-change",
        body: String? = "Some description",
        labels: List<Label> = emptyList()
    ): PullRequest = PullRequest(
        id = 1L,
        number = 1,
        title = "Test PR",
        body = body,
        state = "open",
        htmlUrl = "https://github.com/owner/repo/pull/1",
        user = GitHubUser(login = userLogin, id = 100L, avatarUrl = null, name = null, email = null),
        createdAt = "2024-01-01T00:00:00Z",
        updatedAt = "2024-01-01T00:00:00Z",
        mergedAt = null,
        head = BranchRef(label = "owner:$headRef", ref = headRef, sha = "abc123"),
        base = BranchRef(label = "owner:main", ref = "main", sha = "def456"),
        draft = false,
        labels = labels
    )
}
